services:
  - type: web
    name: weather-app-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false 